preset: psr2

enabled:
  - alias_functions
  - array_element_no_space_before_comma
  - array_element_white_space_after_comma
  - blankline_after_open_tag
  - duplicate_semicolon
  - function_typehint_space
  - include
  - logical_not_operators_with_successor_space
  - method_argument_default_value
  - method_separation
  - multiline_array_trailing_comma
  - multiline_spaces_before_semicolon
  - namespace_no_leading_whitespace
  - newline_after_open_tag
  - new_with_braces
  - no_blank_lines_after_class_opening
  - operators_spaces
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_empty_return
  - phpdoc_order
  - phpdoc_property
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - pre_increment
  - remove_leading_slash_use
  - remove_lines_between_uses
  - return
  - short_array_syntax
  - short_echo_tag
  - single_array_no_trailing_comma
  - single_blank_line_before_namespace
  - single_quote
  - spaces_after_semicolon
  - spaces_before_semicolon
  - spaces_cast
  - standardize_not_equal
  - ternary_spaces
  - trim_array_spaces
  - unused_use
  - whitespacy_lines
